# Materials Simulation with Jupyter Notebooks
<hr style="height:1px;border-top:4px solid #FF8200" />

by Gerd Duscher

Microscopy Facilities<br>
Joint Institute of Advanced Materials<br>
Department of Materials Science & Engineering<br>
The University of Tennessee, Knoxville


# Foreword (ReadME)
This lecture provides information on how to utilize [Jupyter notebooks](https://jupyter.org/) for materials simulations.

I use [anaconda3](https://www.anaconda.com/distribution/) (not miniconda) for linux (most density functional codes need a unix file system). 
On my laptop, I use [linux as a subsystem](https://docs.microsoft.com/en-us/windows/wsl/install-win10) under windows10 and [ubuntu 18.04 LTS](https://www.microsoft.com/en-us/p/ubuntu/9nblggh4msv6?rtc=1&activetab=pivot:overviewtab) 

This lecture is heavily based on the **[Atomic Simulation Environment - ASE](https://wiki.fysik.dtu.dk/ase/)**.
This package makes it possible to use different density functional codes as calculators, and also to use ASE as a post-processor for an already performed calculation. It is very usefull to switch between differnet codes.


The density functional theory (DFT) codes are discussed:
* [GPAW](https://wiki.fysik.dtu.dk/gpaw/)
* [exciting](http://exciting-code.org/)
* [Vasp](https://www.vasp.at/)

The molecular dynamix codes are:

* [ASAP](https://wiki.fysik.dtu.dk/asap/asap)
* [EMT- MD calculator of SAE](https://wiki.fysik.dtu.dk/ase/ase/calculators/emt.html#module-ase.calculators.emt)


Please note, that there is **no programming** required, but the user should not be shy in changing the values of parameters.


The philosophy of these notebooks is that **we use optimized packages** instead of rewritting code! Therefore, the programming language python is used that provides a large number of those packages. The packages semselfs are probably running mostly in Fortran and C, but we do not worry about that.


# Content
This (note-) book is divided in the following sections:

* **Chapter 1: [Introduction](CH1-Introduction.ipynb)**
    * [Python as it is used here](CH1-Introduction_Python.ipynb)
    * [Installation and Prerequesites](CH1-Prerequesites.ipynb)


    
* **Chapter 5: [Simulation](CH5-_Simulations.ipynb)**
    * [Overview](CH5-Overview.ipynb)
    * [Introduction to the *atomic simulation environment* ase](CH5-Intro_ASE.ipynb)

    **Structure**
    * [Building Symmetric Tilt Grain Boundaries](CH5-GrainBoundaryI.ipynb)
    * [Analysing Tilt Grain Boundaries](Analysing_GB.ipynb)
    * [Molecular Dynamics Basics](MolecularDynamics.ipynb)

    **calculators**
    * [GPAW](CH5-GPAW.ipynb)
    * [exciting](CH5-exciting.ipynb)
    * [VASP](CH5-VASP.ipynb)
    

    **Properties**
    * [Calculating Dielectric Function I: Aluminum](CH5-DielectricDFT.ipynb)
    * [Calculating Dielectric Function II: Silicon](CH5-DielectricDFT2.ipynb)
    
    
    

## Introduction to Python as it is used in this lecture

First of all you do not need to program anything, however, you will have to change the values of input parameters inthe code cells. Of course, you are incouraged and to modify the code in order to explore the data analysis methods. 

In this book, we will use the python program language.
For this language, a lot of packages are available that provide algorythms for all common mathematical and statistical needs.

In this book we rely most heavily on the standard numerical and scientific library:<b> numpy and scipy </b>

The philosophy of this book is not to reinvent the wheel but to use those package which are highly optimized.
The code should be as easy to read as possible, which means 
    * the variable names are chosen in the same manner as in the formulas, 
    * the routines of the different packages are not wrapped in others 
    * the code is written step by step and not organized in classes 

# An Example
We will do a lot of vector algebra so as an example we want to compute the angle between two vectors, 

which is calculated by trasnforming the dfinition of the dot product: $\vec{a} \cdot \vec{b} = \left| \vec{a} \right| \left| \vec{b} \right| \cos (\theta) $

$$ \theta = \arccos\left( \frac{\vec{a} \cdot \vec{b}}{\left| \vec{a} \right| \left| \vec{b} \right|} \right)$$

In [2]:
# We need to import the numpy package
import numpy as np

# We define the two vectors
a_vector = [1,1,1]
b_vector = [0,2,1]

# calculate the lengths of the vectors
a_length = np.linalg.norm(a_vector)
b_length = np.linalg.norm(b_vector)

#now the angle between vectors a and b according to above formula
theta = np.arccos(np.dot(a_vector, b_vector) / (a_length * b_length) )

print('The angle between vectors a and b is {0:.2f} degree'.format(np.degrees(theta)) )

The angle between vectors a and b is 39.23 degree


In crystallography we would use the normed (or unit) vectors $\hat{a}$ and $\hat{b}$ which are defined as  $\hat{a} = \frac{\vec{a}}{\left| \vec{a} \right|}$.

The dot product is then the cos of the angle directly: 

$\hat{a} \cdot \hat{b} = \cos (\theta) $

In [4]:
# unit vectors
a_normed = a_vector/a_length
b_normed = b_vector/b_length

theta = np.arccos(np.dot(a_normed, b_normed) )

print('The angle between normed vectors a and b is {0:.2f} degree'.format(np.degrees(theta)) )                 

The angle between normed vectors a and b is 43.09 degree


## Functions
For a task you use more often you might want to define a function to do that task in a reproducable manner.

One always makes sure that one comments those functions, to be 

In [3]:
def angle_between_two_vectors(vector1, vector2):
    """
    
    Calculation of the angle between two vectors of the same dimension throught arccos of the dot product
    
    Input:
    ------
        vector1, vector2: two vectors as lists or numpy arrays
        
    Output:
    -------
        angle: angle between the vectors in radians
    """
    # calculate the lengths of the vectors
    vector1_length = np.linalg.norm(vector1)
    vector2_length = np.linalg.norm(vector2)

    #now the angle between vectors a and b according to above formula
    angle = np.arccos(np.dot(vector1/vector1_length, vector2/vector2_length) )
    return angle #in radians
help(angle_between_two_vectors)
theta = angle_between_two_vectors(a_vector, b_vector)
print('The angle between vectors a: {0} and b: {1} is {2:.2f} degree'.format(a_vector, b_vector, np.degrees(theta)) )          

Help on function angle_between_two_vectors in module __main__:

angle_between_two_vectors(vector1, vector2)
    Calculation of the angle between two vectors of the same dimension throught arccos of the dot product
    
    Input:
    ------
        vector1, vector2: two vectors as lists or numpy arrays
        
    Output:
    -------
        angle: angle between the vectors in radians

The angle between vectors a: [1, 1, 1] and b: [0, 2, 1] is 39.23 degree


## Effective Use of numpy
The real power of numpy will be evident if we code a function that will do the angles of a whole vector field.

In [4]:
def angles_between_consecutive_vectors(vector_field):
    """
    
    Calculation of the angle between two consecutive vectors of the same dimension throught arccos of the dot product
    
    Input:
    ------
        vector_field: a list or numpy array of vectors as lists or numpy arrays
        
    Output:
    -------
        angles: angles between first and all vectors in radians
    """
    
    # calculate the lengths of the vectors
    vector_field_length = np.linalg.norm(vector_field, axis=1) ## The second axis (first is 0) contains the vectors
    #now the angle between vectors a and b according to above formula
    angles = np.arccos(np.outer((vector_field/vector_field_length).T, vector_field[0]/vector_field_length[0]) )
    return angles #in radians

vectors = [a_vector, b_vector, [3,2,1]]
angles = angles_between_consecutive_vectors(vectors)
print(np.degrees(angles))

[[70.52877937 70.52877937 70.52877937]
 [90.         90.         90.        ]
 [        nan         nan         nan]
 [75.03678257 75.03678257 75.03678257]
 [58.90906964 58.90906964 58.90906964]
 [58.90906964 58.90906964 58.90906964]
 [81.12360492 81.12360492 81.12360492]
 [81.12360492 81.12360492 81.12360492]
 [81.12360492 81.12360492 81.12360492]]


/home/nyd/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:18: RuntimeWarning: invalid value encountered in arccos


## Libraries and Classes

The functions introduced in this book are also organized in libraries.

For a more modern programming approach they could also be grouped in classes, but classes  put another layer between notebook and code, which is desirable for abstraction but not necessarily for understanding.

So for the course of this book the functions will be made available in libraries, which can be wrapped in classes for a more monolihic program.

A graphical user interface (GUI) was conciously omitted in this book to encourage the user to mess around in the code.
So please change the vectors and see what the angle will be.

## A word of caution:
A notebook can become confusing, if one does not go through it in a sequential way, because the values of parameters can be changed at any stage in any code cell without the other cells having any knowledge about that.

A program or function will not have that kind of confusing tendency, and therefore, once we understand a topic a comprehensive function will be provided, like in the case of the angle function.
